### ISSUE TITLE
Status code 400

### ISSUE THREAD

**Issue by dustyaltena** [edwarddistel/yahoo-fantasy-baseball-reader#1]
Hi, trying to install this but i'm getting this error after attempting to run index.js.

Any ideas?

`Error in getInitialAuthorization(): Error: Request failed with status code 400`

Note that that error is coming up after changing the 1000ms timeout to 2000ms (it was initially timing out)

**Comment by JarredStanford** [comment]
@dustyaltena a few weeks late but I ran into the same issue. I just got a new auth code from yahoo and it worked. perhaps you have a typo in your code ?

**Comment by cjhaviland** [comment]
+1 for this issue. I am also having trouble. I set everything up and get the League Prefix no problem, but then after a try or two I start getting this error:

`Error in refreshAuthorizationToken(): Error: Request failed with status code 400
Error in getLeaguePrefix(): TypeError: Cannot read property 'fantasy_content' of undefined`

I can solve the issue by getting a new auth code, but that seems tedious. Especially since it stops working after only a few minutes.

**Comment by edwarddistel** [comment]
The tool will automatically refresh the session token for you, you only need to get `YAHOO_AUTH_CODE` once as described in the instructions.

The league prefix for 2020 is 398.

I just refreshed this app for this season, try following the steps from scratch. It should work.
