### ISSUE TITLE
Step 6 not working properly

### ISSUE THREAD

**Issue by griffitp12** [edwarddistel/yahoo-fantasy-baseball-reader#12]
I guess this is a yahoo issue mostly, but after recieving the client key and pasting it into the given URL, yahoo tells me that "something went wrong"

**Comment by edwarddistel** [comment]
Hmm, it definitely works -- are you certain you're using the Client ID/Consumer Key and not the Client Secret/Consumer Secret?

The one you want should be 96 characters long.

Here is an example with a complete made up key of what you should be pasting into your browser:

`https://api.login.yahoo.com/oauth2/request_auth?client_id=eg5yJhl9ZDkzeUGTVUMxQzdxJmQ9WVdrOVEkTk1jekJYU0RR4HNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PWY7&redirect_uri=oob&response_type=code&language=en-us`

Otherwise, I'd just recommend double-checking that the Client ID/Consumer Key you copied and pasted is correct.

Good luck.
