### ISSUE TITLE
std dev stats

### ISSUE THREAD

**Issue by craigham** [edwarddistel/yahoo-fantasy-baseball-reader#2]
Hi,

Do you know if there is a sort type for the standard deviation stats for a player?  I use it for hockey, but I believe that stat is avail for baseball too.

Any idea how to find out valid sort_types for the Yahoo api's ?

thanks
Craig

**Comment by ryus08** [comment]
I believe they use the same values in the query string on the player search page as in the API. I believe during baseball season, I was able to select a filter for P (Probable) in the UI, which changes the url to something like this:

`https://baseball.fantasysports.yahoo.com/b1/{league_id}/players?&sort=AR&sdir=1&status=A&pos=S_P&stat1=S_S_2019&jsenabled=1`

And I believe I found that I could use position `S_P` as the position in[the API, despite nothing documented in the [API docs | https://developer.yahoo.com/fantasysports/guide/players-collection.html] nor in the league settings to indicate that `S_P` is a position, to also filter by probable pitchers. It is the offseason now, so I can't quite check that it returns the right results for baseball, but maybe give it a shot to use the field from the query string in the UI for sort.

In baseball, filtering for Season (std deviation) generates the following url:

`https://baseball.fantasysports.yahoo.com/b1/{league_id}/players?&sort=BI_A&sdir=1&status=A&pos=B&stat1=S_SD_2019&jsenabled=1`

Compare to just Season (Total):

`https://baseball.fantasysports.yahoo.com/b1/{league_id}/players?&sort=BI_A&sdir=1&status=A&pos=B&stat1=S_S_2019&jsenabled=1`

So maybe try `SD` or `S_SD_2019` or something like `standard_deviation` or `std_dev`? Might be a bit more of a stretch for the sort_type since the url clearly doesn't match the API directly for even `season`, but worth a shot.

**Comment by craigham** [comment]
thanks for the suggestions.  I seem to be on my way to work it out now.  I have been inspecting the source on the player page and as you suggested the codes are there.
